#if !defined( STRINGS_H )
#define STRINGS_H

#define STR_NOSPELLS                                        "You don't know any spells."

#define STR_MENU_CARAT                                      ">"
#define STR_MENU_BLANKCARAT                                 " "
#define STR_MENU_TALK                                       "TALK"
#define STR_MENU_STATUS                                     "STATUS"
#define STR_MENU_SEARCH                                     "SEARCH"
#define STR_MENU_SPELL                                      "SPELL"
#define STR_MENU_ITEM                                       "ITEM"
#define STR_MENU_ATTACK                                     "ATTACK"
#define STR_MENU_FLEE                                       "FLEE"
#define STR_MENU_KEY                                        "Key (%u)"
#define STR_MENU_HERB                                       "Herb (%u)"
#define STR_MENU_WING                                       "Chimaera wing (%u)"
#define STR_MENU_FAIRYWATER                                 "Fairy water (%u)"

#define STR_MAP_QUICKSTATSHP                                "HP:%u"
#define STR_MAP_QUICKSTATSMP                                "MP:%u"
#define STR_MAP_QUICKSTATSGOLD                              " G:%u"
#define STR_MAP_QUICKSTATSEXP                               "EX:%u"
#define STR_MAP_STATUSLEVEL                                 "Lvl: %u"
#define STR_MAP_STATUSHP                                    " HP: %u/%u"
#define STR_MAP_STATUSMP                                    " MP: %u/%u"
#define STR_MAP_STATUSATTACK                                "Atk: %u"
#define STR_MAP_STATUSDEFENSE                               "Def: %u"
#define STR_MAP_STATUSAGILITY                               "Agl: %u"
#define STR_MAP_STATUSEXP                                   "Exp: %u"
#define STR_MAP_FOUNDNOTHING                                "You didn't find anything."
#define STR_MAP_NOITEMS                                     "You don't have any items that can be used here."
#define STR_MAP_NODOOR                                      "There is no door here."

#define STR_BATTLE_QUICKSTATSHP                             "HP:%u"
#define STR_BATTLE_QUICKSTATSMP                             "MP:%u"
#define STR_BATTLE_APPROACHINDEFINITEA                      "A %s approaches! Command?"
#define STR_BATTLE_APPROACHINDEFINITEAN                     "An %s approaches! Command?"
#define STR_BATTLE_PLAYERATTACK                             "You attack!"
#define STR_BATTLE_ATTACKENEMY                              "The %s's hit points have been reduced by %u. Command?"
#define STR_BATTLE_ATTACKENEMYDEATH                         "The %s's hit points have been reduced by %u. You have defeated the %s!"
#define STR_BATTLE_PLAYERFLEE                               "You attempt to flee..."
#define STR_BATTLE_FLEESUCCESS                              "You have successfully evaded the %s!"
#define STR_BATTLE_FLEEBLOCK                                "The %s has blocked your escape! Command?"
#define STR_BATTLE_GOLDHAUL                                 "You have gained %u gold."
#define STR_BATTLE_EXPERIENCEHAUL                           "You have gained %u experience."
#define STR_BATTLE_EXPERIENCEGOLDHAUL                       "You have gained %u experience and %u gold."

#define STR_TEMP_TALK                                       "Nobody's there."
#define STR_TEMP_SPELL                                      "You scream 'ABRA KEDAVRA!!', which somehow kills him."
#define STR_TEMP_ITEM                                       "You throw spare change from your pocket, and he dies."

#define STR_ENEMY_SLIME                                     "slime"
#define STR_ENEMY_REDSLIME                                  "red slime"
#define STR_ENEMY_METALSLIME                                "metal slime"
#define STR_ENEMY_DRAKEE                                    "drakee"
#define STR_ENEMY_MAGIDRAKEE                                "magidrakee"
#define STR_ENEMY_DRAKEEMA                                  "drakeema"
#define STR_ENEMY_GHOST                                     "ghost"
#define STR_ENEMY_POLTERGEIST                               "poltergeist"
#define STR_ENEMY_SPECTER                                   "specter"
#define STR_ENEMY_MAGICIAN                                  "magician"
#define STR_ENEMY_WARLOCK                                   "warlock"
#define STR_ENEMY_WIZARD                                    "wizard"
#define STR_ENEMY_SCORPION                                  "scorpion"
#define STR_ENEMY_METALSCORPION                             "metal scorpion"
#define STR_ENEMY_ROGUESCORPION                             "rogue scorpion"
#define STR_ENEMY_DRUIN                                     "druin"
#define STR_ENEMY_DRUINLORD                                 "druinlord"
#define STR_ENEMY_DROLL                                     "droll"
#define STR_ENEMY_DROLLMAGI                                 "drollmagi"
#define STR_ENEMY_SKELETON                                  "skeleton"
#define STR_ENEMY_WRAITH                                    "wraith"
#define STR_ENEMY_WRAITHKNIGHT                              "wraith knight"
#define STR_ENEMY_DEMONKNIGHT                               "demon knight"
#define STR_ENEMY_WOLF                                      "wolf"
#define STR_ENEMY_WOLFLORD                                  "wolflord"
#define STR_ENEMY_WEREWOLF                                  "werewolf"
#define STR_ENEMY_GOLDMAN                                   "goldman"
#define STR_ENEMY_GOLEM                                     "Golem"
#define STR_ENEMY_STONEMAN                                  "stoneman"
#define STR_ENEMY_WYVERN                                    "wyvern"
#define STR_ENEMY_MAGIWYVERN                                "magiwyvern"
#define STR_ENEMY_STARWYVERN                                "starwyvern"
#define STR_ENEMY_KNIGHT                                    "knight"
#define STR_ENEMY_AXEKNIGHT                                 "axe knight"
#define STR_ENEMY_ARMOREDKNIGHT                             "armored knight"
#define STR_ENEMY_GREENDRAGON                               "green dragon"
#define STR_ENEMY_BLUEDRAGON                                "blue dragon"
#define STR_ENEMY_REDDRAGON                                 "red dragon"
#define STR_ENEMY_DRAGONLORDWIZARD                          "Dragonlord Wizard"
#define STR_ENEMY_DRAGONLORDDRAGON                          "Dragonlord Dragon"

#define STR_TREASURE_GOLDCOLLECTED                          "The chest contains %u gold!"
#define STR_TREASURE_GOLDDENIED                             "The chest contains %u gold, but you can't carry any more gold."
#define STR_TREASURE_ITEMCOLLECTED                          "The chest contains %s!"
#define STR_TREASURE_ITEMDENIED                             "The chest contains %s, but you can't carry any more of these."

#define STR_ITEM_AKEY                                       "a key"
#define STR_ITEM_ANHERB                                     "an herb"
#define STR_ITEM_AWING                                      "a chimaera wing"
#define STR_ITEM_FAIRYWATER                                 "fairy water"
#define STR_ITEM_ERDRICKSTABLET                             "Erdrick's Tablet"
#define STR_ITEM_THESTONEOFSUNLIGHT                         "the Stone of Sunlight"

// we should never see this, but just in case
#define STR_ITEM_ERR                                        "The chest is a lie!"

#endif // STRINGS_H
